from celery import Celery
from datetime import datetime

# SentinelAI Imports
from database import SessionLocal
from models import Scan, ScanStatus, Mission
from analysis import calculate_risk_score, generate_remediation_plan, calculate_confidence_score
import yaml
from engine.nmap_plugin import NmapPlugin
from engine.subdomain_plugin import SubdomainPlugin
from engine.generic_plugin import GenericBinaryPlugin
from engine.certificate_plugin import CertificatePlugin
try:
    from engine.browser_plugin import BrowserPlugin
    BROWSER_PLUGIN_AVAILABLE = True
except ImportError:
    BROWSER_PLUGIN_AVAILABLE = False
from engine.response import trigger_response_engine
from intelligence.graph import graph_db
from evidence import setup_bucket, upload_evidence
import json
from intelligence.agents import SentinelAgents, SentinelTasks
from crewai import Crew, Process

celery_app = Celery(
    "sentinel_tasks",
    broker="redis://redis:6379/0",
    backend="redis://redis:6379/1"
)

# --- NEW: Celery Beat Configuration ---
from celery.schedules import crontab
celery_app.conf.beat_schedule = {
    "poll-scheduled-scans": {
        "task": "engine.poll_scheduled_scans",
        "schedule": 60.0, # Every 60 seconds
    },
}
celery_app.conf.timezone = 'UTC'

def load_registry() -> dict:
    """
    Dynamically builds the PLUGIN_REGISTRY from tools_registry.yaml.
    For schema-enabled tools (with base_command + parameters), the plugin
    receives the full schema so it can validate AI-generated args at runtime.
    """
    # Dedicated plugins with custom parsers take priority over the YAML schema
    registry = {
        "nmap":      NmapPlugin(),
        "subdomain": SubdomainPlugin(),
        "certcheck": CertificatePlugin(),
    }
    
    if BROWSER_PLUGIN_AVAILABLE:
        registry["browser"] = BrowserPlugin()

    try:
        with open("engine/tools_registry.yaml", "r") as f:
            config = yaml.safe_load(f)

        for name, info in config.get("tools", {}).items():
            if name in registry:
                continue  # Keep dedicated implementations

            # Support both legacy (command:) and schema-based (base_command: + parameters:)
            legacy_cmd = info.get("command", f"{name} {{target}}")
            base_command = info.get("base_command")
            parameters = info.get("parameters", {})
            description = info.get("description", "")

            registry[name] = GenericBinaryPlugin(
                name=name,
                command_template=legacy_cmd,
                base_command=base_command,
                parameters=parameters,
                description=description,
            )

    except FileNotFoundError:
        print("[WARN] tools_registry.yaml not found. Using core plugins only.")

    return registry

PLUGIN_REGISTRY = load_registry()


@celery_app.task(bind=True, name="engine.run_scan_job")
def run_scan_job(self, scan_id: int, target: str, tool_name: str, args: dict = None):
    """
    Core worker task. Executes a single tool scan and stores results + AI analysis.
    - args: optional schema-validated parameters generated by the AI orchestrator
    """
    # Open a dedicated database session for this background worker
    db = SessionLocal()
    scan_record = db.query(Scan).filter(Scan.id == scan_id).first()
    
    if not scan_record:
        db.close()
        return {"error": "Scan ID not found in database"}

    # 1. Update Status to RUNNING with start timestamp
    scan_record.status = ScanStatus.RUNNING
    scan_record.started_at = datetime.utcnow()
    db.commit()
    
    plugin = PLUGIN_REGISTRY.get(tool_name.lower())
    if not plugin:
        scan_record.status = ScanStatus.FAILED
        scan_record.findings = {"error": f"Tool '{tool_name}' is not supported."}
        db.commit()
        db.close()
        return
        
    # 2. Validate Rules of Engagement
    if not plugin.validate_roe(target):
        scan_record.status = ScanStatus.FAILED
        scan_record.findings = {"error": "Target violates Rules of Engagement."}
        db.commit()
        db.close()
        return

    # 3. Execute and Normalize
    try:
        # Initialize evidence bucket on first run
        setup_bucket()
        
        raw_output = plugin.execute(target, args=args)
        normalized_findings = plugin.normalize(raw_output)
        
        # 3.5 Threat Intel IOC Lookup for target
        try:
            from intelligence.threat_intel import threat_intel
            import re
            is_ip = re.match(r"^\d{1,3}(\.\d{1,3}){3}$", target)
            ioc_type = "ip" if is_ip else "domain"
            ti_result = threat_intel.lookup_ioc(target, ioc_type)
            if ti_result and ti_result.get("malicious"):
                normalized_findings["threat_intel"] = ti_result
        except Exception as e:
            print(f"[WORKER] TI lookup failed: {e}")
            
        # Capture Evidence to MinIO
        evidence_urls = []
        if raw_output:
            url = upload_evidence(scan_id, f"{tool_name}_raw.txt", str(raw_output))
            if url:
                evidence_urls.append(url)
                
        # Append Execution to Decision Log if part of a mission
        if scan_record.mission_id:
            mission = db.query(Mission).filter(Mission.id == scan_record.mission_id).first()
            if mission:
                log_copy = list(mission.decision_log)
                log_copy.append({
                    "timestamp": datetime.utcnow().isoformat(),
                    "action": f"{tool_name} completed",
                    "reason": f"Tool executed in sandbox. Findings count: {len(normalized_findings)}",
                    "confidence": ""
                })
                mission.decision_log = log_copy
                db.commit()

        # 4. Score Risk (CVSS-lite)
        risk = calculate_risk_score(normalized_findings, tool_name)
        
        # 4.5. Verification & Confidence Score
        cross_validated = False
        if risk in ["MEDIUM", "HIGH", "CRITICAL"]:
            print(f"[WORKER] Triggering Verifier Agent for {scan_id} (Risk: {risk})...")
            try:
                # Smart Verification Routing
                tool_lower = tool_name.lower()
                if tool_lower in ["subdomain", "amass", "sublist3r"]:
                    verifier_agent = SentinelAgents.dns_agent()
                elif tool_lower in ["certcheck"]:
                    verifier_agent = SentinelAgents.certificate_agent()
                elif tool_lower in ["httpx", "ffuf", "gobuster", "nikto"]:
                    verifier_agent = SentinelAgents.fingerprint_agent()
                elif tool_lower in ["nuclei", "trivy", "grype"]:
                    verifier_agent = SentinelAgents.vuln_agent()
                else:
                    verifier_agent = SentinelAgents.exploit_agent()
                    
                verification_task = SentinelTasks.verification_task(verifier_agent, normalized_findings, tool_name)
                crew = Crew(agents=[verifier_agent], tasks=[verification_task], process=Process.sequential, verbose=False)
                result = crew.kickoff()
                raw_result = str(result).strip()
                if raw_result.startswith("```"):
                    raw_result = raw_result.split("```")[1]
                    if raw_result.startswith("json"):
                        raw_result = raw_result[4:]
                verification_json = json.loads(raw_result)
                cross_validated = verification_json.get("is_verified", False)
                print(f"[WORKER] Verifier Agent complete. Cross-validated: {cross_validated}")
                
                # Append Verification to Decision Log
                if scan_record.mission_id:
                    mission = db.query(Mission).filter(Mission.id == scan_record.mission_id).first()
                    if mission:
                        log_copy = list(mission.decision_log)
                        log_copy.append({
                            "timestamp": datetime.utcnow().isoformat(),
                            "action": f"Verification performed for {tool_name}",
                            "reason": "Cross-validated findings with LLM analysis",
                            "confidence": "90%" if cross_validated else "Low"
                        })
                        mission.decision_log = log_copy
                        db.commit()
                        
            except Exception as e:
                print(f"[WORKER] Verifier Agent failed: {e}")
                
        evidence_captured = len(evidence_urls) > 0
        confidence = calculate_confidence_score(normalized_findings, cross_validated, evidence_captured=evidence_captured)
        
        # 5. Generate AI Remediation Report (Groq)
        print(f"[WORKER] Generating remediation plan for scan {scan_id} (risk: {risk})...")
        remediation = generate_remediation_plan(normalized_findings, tool_name, risk)
        
        # Embed remediation into findings payload
        normalized_findings["remediation_plan"] = remediation
        normalized_findings["risk_level"] = risk
        
        # 6. Save Results to Database
        scan_record.status = ScanStatus.COMPLETED
        scan_record.findings = normalized_findings
        scan_record.risk_score = risk
        scan_record.confidence_score = confidence
        scan_record.cross_validated = cross_validated
        scan_record.evidence_links = evidence_urls
        scan_record.completed_at = datetime.utcnow()
        
        # 7. Push to Knowledge Graph
        try:
            org_id = scan_record.asset.organization_id
            graph_db.add_scan_findings(org_id, target, scan_id, tool_name, risk, normalized_findings)
        except Exception as e:
            print(f"[WORKER] Failed to push to Knowledge Graph: {e}")

        # 8. Trigger Action & Response Engine
        try:
            trigger_response_engine(scan_id, target, risk, normalized_findings)
        except Exception as e:
            print(f"[WORKER] Failed to trigger response engine: {e}")
        
    except Exception as e:
        print(f"[WORKER ERROR] {e}")
        if scan_record:
            scan_record.status = ScanStatus.FAILED
            scan_record.findings = {"error": str(e)}
        
    finally:
        # Extract the final status value into a plain string BEFORE closing the session
        if scan_record:
            final_status_str = scan_record.status.value if hasattr(scan_record.status, 'value') else str(scan_record.status)
            db.commit()
        else:
            final_status_str = "failed"
            
        if db:
            db.close()
        
    # Safely return the plain string instead of the database object property
    return {"scan_id": scan_id, "status": final_status_str}

@celery_app.task(name="engine.poll_scheduled_scans")
def poll_scheduled_scans():
    """
    Periodic task triggered by Celery Beat every 60s.
    Checks the scheduled_scans table for any scans due to run.
    """
    from models import ScheduledScan, Scan, Asset
    from croniter import croniter
    
    db = SessionLocal()
    try:
        now = datetime.utcnow()
        # Find scans that are due (next_run <= now)
        due_scans = db.query(ScheduledScan).filter(ScheduledScan.next_run <= now).all()
        
        for s in due_scans:
            print(f"[BEAT] Triggering scheduled scan {s.id} for {s.target} ({s.tool})")
            
            # 1. Ensure Asset exists
            asset = db.query(Asset).filter(Asset.target == s.target, Asset.organization_id == s.organization_id).first()
            if not asset:
                asset = Asset(target=s.target, asset_type="domain_or_ip", organization_id=s.organization_id)
                db.add(asset)
                db.flush()
                
            # 2. Create actual Scan record
            new_scan = Scan(
                asset_id=asset.id,
                status=ScanStatus.QUEUED,
                tool_used=s.tool
            )
            db.add(new_scan)
            db.flush()
            
            # 3. Queue the worker job
            run_scan_job.delay(new_scan.id, s.target, s.tool, None)
            
            # 4. Update ScheduledScan timestamps
            s.last_run = now
            # Calculate next run using croniter
            cron = croniter(s.cron_expression, now)
            s.next_run = cron.get_next(datetime)
            
        db.commit()
    except Exception as e:
        db.rollback()
        print(f"[BEAT] Failed to poll scheduled scans: {e}")
    finally:
        db.close()