import asyncio
from typing import TypedDict, List, Dict, Any
from langgraph.graph import StateGraph, END

# Import core configurations and memory
from core.config import MAX_AGENT_CYCLES
from core.memory import memory_store

# Import autonomous agents
from agents.recon_agent import AdvancedReconAgent
from agents.exploit_runner import simulate_active_testing, test_idor_vulnerability, execute_nuclei_scan
from agents.hypothesis import generate_hypotheses
from agents.grc_reporter import grc_report_node
from agents.msf_orchestrator import msf_weaponization_node

# Import the centralized streaming logger
from core.logger import stream_log

# 1. Define the Global Agent State (Updated for MCP tracking)
class MythosState(TypedDict):
    target: str
    app_model: Dict[str, Any]
    hypotheses: List[Dict[str, Any]]
    confirmed_exploits: List[Dict[str, Any]]
    chained_impacts: List[str]
    cycle_count: int
    session_a_headers: Dict[str, str]
    session_b_headers: Dict[str, str]
    nuclei_findings: List[Dict[str, Any]]
    report_generated: bool
    available_mcp_tools: List[str]  # TRACKS DISCOVERED MCP CAPABILITIES

# 2. Recon Node
async def recon_node(state: MythosState) -> Dict:
    await stream_log(f"\n[RECON AGENT] Initializing advanced crawl on {state['target']}")
    
    recon_agent = AdvancedReconAgent(state["target"], max_depth=3)
    recon_data = await recon_agent.crawl()
    app_model = {
        "endpoints": recon_data["endpoints"],
        "forms": recon_data["forms"],
        "trust_boundaries": ["unauthenticated"],
    }
    
    await stream_log(f"[RECON AGENT] Crawl Complete. Found {len(recon_data['endpoints'])} endpoints.")
    return {"app_model": app_model, "cycle_count": state.get("cycle_count", 0) + 1}

# 3. Hypothesis Brain Node (Upgraded to Claude 3.5 Sonnet context)
async def hypothesis_node(state: MythosState) -> Dict:
    await stream_log("\n[HYPOTHESIS] Reasoning over Application Model Graph...")
    await stream_log(f"  [MCP CONTEXT] Active tool capability matrix: {state.get('available_mcp_tools', [])}")

    app_model = state["app_model"]
    endpoints_found = len(app_model.get("endpoints", []))
    await stream_log(f"  [HYPOTHESIS] Working from {endpoints_found} real crawled endpoints.")

    # Generate AI hypotheses using Claude 3.5 Sonnet
    ai_hypotheses = await generate_hypotheses(app_model)
    await stream_log(f"  [OK] {len(ai_hypotheses)} hypotheses generated by Claude 3.5 Sonnet.")

    # Add Nuclei baseline scan
    nuclei_hypothesis = {
        "cwe": "CWE-200",
        "name": "Nuclei: Exposure & Misconfiguration Check",
        "target_endpoint": app_model.get("base_url", state["target"]),
        "attack_strategy": "nuclei_template_scan",
        "reasoning": "Executing DAST templates against observed base URL via MCP transport wrapper."
    }

    return {"hypotheses": ai_hypotheses + [nuclei_hypothesis]}

# 4. Exploit Validation Node
async def testing_node(state: MythosState) -> Dict:
    await stream_log(f"\n[VALIDATION] Executing tests for {len(state['hypotheses'])} hypotheses...")
    new_confirmed = []
    new_nuclei_findings = []
    
    for hyp in state["hypotheses"]:
        strategy = hyp.get("attack_strategy", "")
        cwe = hyp.get("cwe", "")
        
        # Query ChromaDB for past successful payloads
        past_payloads = memory_store.retrieve_payload_patterns(cwe)
        if past_payloads:
            await stream_log(f"  [MEMORY] Injecting {len(past_payloads)} historical payloads from ChromaDB.")

        # Intelligence Routing
        if strategy == "dual_session_authorization_bypass" or "639" in cwe or "idor" in hyp.get("name", "").lower():
            await stream_log(f"[TESTING] Checking IDOR vulnerability at {hyp.get('target_endpoint')}")
            result = await test_idor_vulnerability(
                hyp, 
                state.get("session_a_headers", {}), 
                state.get("session_b_headers", {})
            )
        elif strategy == "nuclei_template_scan" or "nuclei" in hyp.get("name", "").lower():
            await stream_log(f"\n[AGENT COMMANDER] Delegating testing to Nuclei Engine -> Target: {state['target']}")
            result = await execute_nuclei_scan(hyp, state["target"])
            if "raw_findings" in result:
                new_nuclei_findings.extend(result["raw_findings"])
        else:
            await stream_log(f"[TESTING] Active fuzzing for {cwe} at {hyp.get('target_endpoint', state['target'])}")
            result = await simulate_active_testing(hyp)
        
        # Record Findings
        if result.get("is_vulnerable"):
            await stream_log(f"  [!!!] EXPLOIT SUCCESS: {cwe} confirmed at {hyp.get('target_endpoint')}")
            new_confirmed.append(hyp)
            hyp["reasoning"] = result.get("notes", "Confirmed via testing payload") 
            memory_store.store_successful_exploit(
                cwe=cwe,
                target_endpoint=hyp.get("target_endpoint", state["target"]),
                payload=result.get("payload_used", "N/A"),
                context=result.get("notes", "N/A")
            )

    return {
        "confirmed_exploits": state.get("confirmed_exploits", []) + new_confirmed,
        "nuclei_findings": state.get("nuclei_findings", []) + new_nuclei_findings
    }

# 5. Vulnerability Chaining Node
async def chaining_node(state: MythosState) -> Dict:
    await stream_log("\n[CHAINING] Evaluating exploit chains for critical impact...")
    chains = []
    total_vulns = len(state.get("confirmed_exploits", [])) + len(state.get("nuclei_findings", []))
    
    if total_vulns >= 2:
        await stream_log("  [*] Chain Discovered: Potential multi-stage exploit vector identified!")
        chains.append("Complex Chain Achieved via Multiple Vulnerabilities")
    else:
        await stream_log("  [-] Insufficient vulnerabilities for complex chaining.")
        
    return {"chained_impacts": state.get("chained_impacts", []) + chains}

# 6. Graph Routing Logic
def should_continue(state: MythosState) -> str:
    if len(state.get("confirmed_exploits", [])) > 0 or len(state.get("nuclei_findings", [])) > 0:
        print("\n[ORCHESTRATOR] Exploits confirmed. Exiting fuzzing loop.")
        return "end"

    if state["cycle_count"] < MAX_AGENT_CYCLES:
        print(f"\n[ORCHESTRATOR] Cycle {state['cycle_count']} complete — refining strategy...")
        return "recon"

    print(f"\n[ORCHESTRATOR] Max cycles ({MAX_AGENT_CYCLES}) reached.")
    return "end"

# 7. Compile LangGraph
def build_mythos():
    workflow = StateGraph(MythosState)
    
    # Register all nodes
    workflow.add_node("recon", recon_node)
    workflow.add_node("hypothesis", hypothesis_node)
    workflow.add_node("testing", testing_node)
    workflow.add_node("chaining", chaining_node)
    workflow.add_node("weaponize", msf_weaponization_node)
    workflow.add_node("grc_report", grc_report_node)
    
    # Define standard execution flow
    workflow.set_entry_point("recon")
    workflow.add_edge("recon", "hypothesis")
    workflow.add_edge("hypothesis", "testing")
    workflow.add_edge("testing", "chaining")
    
    # Conditional Routing Loop
    workflow.add_conditional_edges("chaining", should_continue, {
        "recon": "recon", 
        "end": "weaponize"
    })
    
    workflow.add_edge("weaponize", "grc_report")
    workflow.add_edge("grc_report", END)
    
    return workflow.compile()