"""Add started_at to Scan

Revision ID: 550b6e8a1bdb
Revises: b5a94e574c9b
Create Date: 2026-06-28 17:23:08.653894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550b6e8a1bdb'
down_revision: Union[str, Sequence[str], None] = 'b5a94e574c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'started_at')
    # ### end Alembic commands ###
