"""add mission and evidence

Revision ID: 92084d1019a0
Revises: eafcf39e4218
Create Date: 2026-06-29 09:05:08.677751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92084d1019a0'
down_revision: Union[str, Sequence[str], None] = 'eafcf39e4218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_target'), 'missions', ['target'], unique=False)
    op.add_column('scans', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('evidence_links', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'scans', 'missions', ['mission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_column('scans', 'evidence_links')
    op.drop_column('scans', 'mission_id')
    op.drop_index(op.f('ix_missions_target'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
