"""add confidence score

Revision ID: eafcf39e4218
Revises: e3d4e5f6g7h8
Create Date: 2026-06-29 08:40:03.773616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafcf39e4218'
down_revision: Union[str, Sequence[str], None] = 'e3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('cross_validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'cross_validated')
    op.drop_column('scans', 'confidence_score')
    # ### end Alembic commands ###
